services:
  front:
    build: ./frontend
    depends_on:
      - api
    ports:
      - 5173:5173
    networks:
      - custom_network
  api:
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - custom_network
    environment:
      - MONGO_URL=mongodb+srv://anshpatel1605:W7acBzFLLXWSVntx@cluster0.ckn5ucf.mongodb.net/your_database?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb-1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: anshpatel1605
      MONGO_INITDB_ROOT_PASSWORD: W7acBzFLLXWSVntx
    networks:
      - custom_network
    # volumes:
    #   - mongo-data:/data/db
      
networks:
  custom_network:
    driver: bridge